all:
  children:
    open_project:
      hosts:
        openproject:
          ansible_host: 192.168.50.50
    test_servers:
      hosts:
        test_vm1:
          ansible_host: 192.168.50.55
        test_vm2:
          ansible_host: 192.168.50.54
