---
- name: ensure known unauthorized users are removed
  ansible.builtin.user:
    name: "{{ user }}"
    state: absent
    remove: true
  loop:
    - games
  loop_control:
    loop_var: user

- name: ensure known unauthorized groups are removed
  ansible.builtin.group:
    name: "{{ group }}"
    state: present
    force: true
  loop:
    - games
  loop_control:
    loop_var: group
