- name: set vm hostname 
  ansible.builtin.hostname: 
    name: "{{ groups['open_project'][0] }}"

- name: Remove conflicting Docker repo entry if it exists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent
  become: true

- name: Install prerequisites for Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true
  become: true

- name: Add Docker’s official GPG key (dearmored)
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: true

- name: Add Docker APT repository (Ubuntu Jammy)
  apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu jammy stable
    filename: docker
    state: present
    update_cache: true
  become: true

- name: Install Docker Engine and Compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true

- name: Verify Docker Compose v2 installation
  command: docker compose version
  register: compose_version
  changed_when: false

- name: Show Docker Compose version
  debug:
    msg: "{{ compose_version.stdout }}"

- name: Clone openproject-deploy repository
  ansible.builtin.git:
    repo: https://github.com/opf/openproject-deploy
    dest: /opt/openproject
    version: stable/15
    force: yes
    update: yes

- name: Ensure python3-pip is installed
  apt:
    name: python3-pip
    state: present
    update_cache: true
  become: true

- name: Install Python Docker SDK and dependencies
  ansible.builtin.pip:
    name:
      - docker
      - requests
    executable: pip3
  become: true

- name: deliver openproject configuration
  ansible.builtin.template:
    src: env.j2
    dest: /opt/openproject/.env
    owner: root
    group: root
    mode: '0644'
  become: true

- name: make persistent openproject data directory
  ansible.builtin.file:
    path: "{{ op_path }}"
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'
    recurse: true
  loop:
    - /var/openproject
    - /var/openproject/assets
    - /var/openproject/lib/postgresql/data
  loop_control:
    loop_var: op_path
  become: true

- name: Start OpenProject containers with Docker Compose
  ansible.builtin.shell: |
    docker compose up -d
  become: true
  args:
    chdir: /opt/openproject/


